version: '3'
services:
  sw:
    image: nginx:alpine
    container_name: sw
    volumes:
      - ./serviceWorker:/usr/share/nginx/html
    ports:
      - "1501:80"
  sw2:
    image: nginx:alpine
    container_name: sw2
    volumes:
      - ./serviceWorker:/usr/share/nginx/html
    ports:
      - "1503:80"
  http:
    image: node:10
    container_name: http
    volumes:
      - ./http:/app
    ports:
      - "1502:80" 
